### ISSUE TITLE
Postcss autoprefixer

### ISSUE THREAD

**Issue by meneerprins** [devlocker/breakfast#12]
I'm quite new to brunch asset building etc. and I really would like to try out Postcss. But I can't seem to get autoprefixer to work, not sure if it's an issue with breakfast, brunch, Postcss-brunch or I'm doing something wrong but anyone knows how to get it working? (with .scss files)

**Comment by PatKoperwas** [comment]
Hey @meneerprins I ran into the same issue. Here's how to get it working (with SCSS support).

Install the [brunch-postcss](https://github.com/brunch/postcss-brunch) plugin and [Autoprefixer](https://github.com/postcss/autoprefixer) with:

```
npm install --save-dev brunch-postcss autoprefixer
```

Now, apparently there [is an issue](https://github.com/brunch/postcss-brunch/issues/31) with the latest version of the plugin. So once it finishes installing open `package.json` and change the line

```
"postcss-brunch": "^2.0.5",
```

to

```
"postcss-brunch": "~0.5.0",
```

That will downgrade the package to a version that works.

Then enable the plugin in your `brunch-config` but adding the following into the `plugins` section:

```
postcss: {
    processors: [
      require('autoprefixer')(['last 8 versions']),
      require('csswring')()
    ]
  }
```

The [documentation](https://github.com/brunch/postcss-brunch) for the plugin has more info if you need it.

Hopefully that resolves your issue!

**Comment by meneerprins** [comment]
Thanks a lot!

**Comment by ryan-mahoney** [comment]
I down-graded and this is working for me now also. Does anyone know if this is still the only solution?

**Comment by PatKoperwas** [comment]
@ryan-mahoney for the time being looks like yes it is. There seems to be quite a bit of work being done however so this should get resolved eventually.

Check out the links referenced in https://github.com/brunch/brunch/issues/1619#issuecomment-286219478 for a bit more detail / progress

**Comment by meneerprins** [comment]
I just implemented breakfast/brunch into a pretty big webapp and I really like it, still got an issue with postcss and sourcemaps, anyone knows how to fix that?

**Comment by PatKoperwas** [comment]
@meneerprins feel free to open an issue detailing what the issue is or shoot me email patrick@devlocker.io.

I am happy to take a look and help debug.
