### ISSUE TITLE
Production issues

### ISSUE THREAD

**Issue by kin9puppy** [devlocker/breakfast#14]
I am trying to make the simplest implementation work in `production` environment. 

In browser console:
- Getting `Failed to load resource: the server responded with a status of 404 (Not Found)` during production for `assets/app.js`, `javascripts/app.js` and `stylesheets/app.css`. 
- Additionally seeing `Uncaught ReferenceError: require is not defined` 

The compiled assets exist.

Pretty sure the Asset Pipeline is causing issues here (everything works easily in development), can you suggest the proposed method of solving this?

**Comment by kin9puppy** [comment]
I ended up outputting brunch's compiled files to `app/assets/javascripts` before the pipeline builds (`application.rb`), which works fine, but there may be a more idiomatic way to accomplish the same thing.

**Comment by PatKoperwas** [comment]
Hmm yeah there is probably something funny going on. Mind giving me the following information?

1. Are you deploying with Heroku, Capistrano or running in production locally (on your machine, `RAILS_ENV=production bin/rails s`
2. Breakfast Gem Version (check Gemfile.lock)

**Comment by kin9puppy** [comment]
Thanks @PatKoperwas ...

```
    breakfast (0.4.2)
      actioncable (~> 5.0)
      listen (>= 3.0)
      rails (~> 5.0)
```

Deploying with CircleCI onto Heroku

**Comment by PatKoperwas** [comment]
@kin9puppy Oh I think it might be an error in my documentation...

Can you run the following?


```
heroku buildpacks:clear
```
That will clear all buildpacks. Then we'll add Ruby first, then the breakfast build pack.

```
heroku buildpacks:add heroku/ruby
heroku buildpacks:add --index 2 https://github.com/devlocker/heroku-buildpack-breakfast.git
```
