### ISSUE TITLE
Vue Config Docs missing step.

### ISSUE THREAD

**Issue by jgonzalezd** [devlocker/breakfast#16]
I am starting with vue but I have been working with Rails for some years now. Almost give up with Brunch because I struggled for 2 days to figure out how to make them work. 

If one follow the instructions as here http://breakfast.devlocker.io/examples/vue.html wont be able to make it work. It's missing the following:

1. Create directory `assets` under `/public` directory before firing up the `rails s` command

2. Import MUST be capitalized if your file is `app/frontend/components/Hello.vue`. So in `app.js` put:
    `import Hello from './components/Hello';` instead of
    `import Hello from './components/hello';`

3. You MUST add this to the `brunch-fonfig.js`
```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'app.js': /^app\/frontend\/js\//,
        'vendor.js': /^(?!app\/frontend\/js)/
      }
    },
    stylesheets: {
      joinTo: 'app.css'
    },
    templates: {    <<============ MISSING THING!
      joinTo: {
        'app.js': 'app/frontend/js/components/*.vue'
      }
    }
  },
...rest of file
```

More info on second issue here https://github.com/nblackburn/vue-brunch/issues/5

PD: To anyone having this issue I just put this question on stackoverflow with link to a working example on my github 
http://stackoverflow.com/a/42057658/1248725

**Comment by PatKoperwas** [comment]
Hey thanks for pointing out the flaws in the documentation. I've gone ahead and updated the docs to reflect your changes. 

Also now with v0.5.0 the [templates option](https://github.com/devlocker/breakfast/pull/15/commits/de19d5c4bb3e4d2ff88754b22f029a8f0b369269#diff-36b58e86bbd2dab2d4d4ce56ed7ccbbdR12) is included by default.

And with a patched version 0.5.1 Breakfast will now create public/assets if it does not already exist.
