### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by koriroys** [devlocker/breakfast#17]
Hello! Is there something special I need to configure to get in-template sass/scss to work?

Trying this currently:
```
<style lang="scss">
li
  color: red
</style>
```

but the error is: `error: Compiling of app/frontend/js/components/video-tags.vue failed. Error: Invalid CSS after "": expected 1 selector or at-rule, was "li"`

Cheers.

**Comment by PatKoperwas** [comment]
I'm assuming this is for a `.vue` file?

If that's the case here's what you'll need.

```js
// Make sure the latest version of vue-brunch is installed
yarn upgrade vue-brunch

// In your brunch-config.js add the following in the plugins section
plugins: {
  // other plugins...
  vue: {
    sass: {
      indentedSyntax: true
    }
  }
}
```

**Comment by PatKoperwas** [comment]
By default scss / sass compilers assume the `scss` syntax, so instead of 

```sass
li
  color: red
```

```scss
li {
  color: red
}
```

The `indentedSyntax` option just tells the compiler to process using the `SASS` syntax

**Comment by koriroys** [comment]
@PatKoperwas Yes it's for a .vue single template component. I should have specified that better.

Wow, didn't even realize indentedSyntax was a thing. Thank you, works great now. I figured it wasn't actually a bug, but something simple that you might know off the top of your head.

Thanks again mate.
