### ISSUE TITLE
ActiveRecord::AdapterNotSpecified: 'staging' database is not configured.

### ISSUE THREAD

**Issue by Rwobbema** [devlocker/breakfast#19]
I'm having some trouble with deploying my Rails application with Breakfast to Heroku. Before I installed breakfast I didn't had to specify any database configuration for the staging and production environments. Heroku was handling this with the `ENV['DATABASE_URL']` variable. But now when I want to deploy my Rails app to staging It's giving me this error:

`ActiveRecord::AdapterNotSpecified: 'staging' database is not configured.`

This error shows up during this rake task: 

`breakfast:assets:build_production`

I have the feeling that the environment variables are not set. Because when I add all the staging database configuration directly into the configuration file, it gives me the error that Redis is trying to connect with localhost.

Does anyone have an idea how to solve this problem?

**Comment by PatKoperwas** [comment]
@Rwobbema I'm in the process of simplifying Heroku deployments (by getting rid of the custom buildpack), do you mind trying the following steps?

1. Use the unreleased `v.0.6.0 branch:

```
# In Gemfile change gem "breakfast" to
gem "breakfast", git: "https://github.com/devlocker/breakfast", branch: "v0.6.0"
```

2. Run the following commands to reset your buildpacks

```
heroku buildpacks:clear
heroku buildpacks:set heroku/nodejs --index 1
heroku buildpacks:set heroku/ruby --index 2
```

Then just commit those changes and push to Heroku. Let me know if that works

**Comment by Rwobbema** [comment]
Hi @PatKoperwas,

Yes, I tried this yesterday and to be sure now again. The deployment succeeded but unfortunately the assets aren't compiled.

**Comment by PatKoperwas** [comment]
Okay, any chance you can paste the Heroku deploy log?

**Comment by Rwobbema** [comment]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x via semver.io...
       Downloading and installing node 6.10.1...
       Using default npm version: 3.10.10
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.21.3)...
       Installed yarn 0.21.3
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.21.3
       warning No license field
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 14.26s.
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.3
-----> Installing dependencies using bundler 1.13.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/..........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Using rake 12.0.0
       Using concurrent-ruby 1.0.4
       Using i18n 0.8.0
       Using minitest 5.10.1
       Using thread_safe 0.3.5
       Using builder 3.2.3
       Using erubis 2.7.0
       Using mini_portile2 2.1.0
       Using rack 2.0.1
       Using nio4r 1.2.1
       Using websocket-extensions 0.1.2
       Using mime-types-data 3.2016.0521
       Using arel 7.1.4
       Using excon 0.55.0
       Using multi_json 1.12.1
       Using connection_pool 2.2.1
       Using redis 3.3.3
       Using aws-sigv4 1.0.0
       Using jmespath 1.3.1
       Using bcrypt 3.1.11
       Using rb-fsevent 0.9.8
       Using ffi 1.9.17
       Using ruby_dep 1.5.0
       Using bundler 1.13.7
       Using method_source 0.8.2
       Using thor 0.19.4
       Using browser 2.3.0
       Using chartkick 2.2.2
       Using climate_control 0.1.0
       Using multi_xml 0.6.0
       Using coffee-script-source 1.12.2
       Using execjs 2.7.0
       Using currencies 0.4.2
       Using i18n_data 0.7.0
       Using unicode_utils 1.4.0
       Using mimemagic 0.3.2
       Using multipart-post 2.0.0
       Using tilt 2.0.6
       Using hashie 3.5.3
       Using json 1.8.6
       Using jwt 1.5.6
       Using mollie-api-ruby 2.1.0
       Using os 0.9.6
       Using pg 0.19.0
       Using puma 3.7.1
       Using rack-cors 0.4.1
       Using rdoc 4.3.0
       Using safety_mailer 0.0.10
       Using settingslogic 2.0.9
       Using will_paginate 3.1.5
       Using i18n-active_record 0.1.2
       Using vanity 2.2.7
       Using tzinfo 1.2.2
       Using sitemap_generator 5.3.1
       Using nokogiri 1.7.0.1
       Using rack-protection 1.5.3
       Using rack-test 0.6.3
       Using sprockets 3.7.1
       Using websocket-driver 0.6.5
       Using mime-types 3.1
       Using heroku-api 0.4.2
       Using heroics 0.0.19
       Using redis-namespace 1.5.3
       Using aws-sdk-core 2.7.11
       Using rb-inotify 0.9.8
       Using cocaine 0.5.8
       Using httparty 0.14.0
       Using countries 1.2.5
       Using coffee-script 2.4.1
       Using faraday 0.10.1
       Using sort_alphabetical 1.1.0
       Using haml 4.0.7
       Using omniauth 1.6.1
       Using sdoc 0.4.2
       Using activesupport 5.0.1
       Using loofah 2.0.3
       Using sidekiq 4.2.9
       Using platform-api 0.8.0
       Using mail 2.6.4
       Using listen 3.1.5
       Using oauth2 1.3.0
       Using country_select 2.5.2
       Using rails-dom-testing 2.0.2
       Using globalid 0.3.7
       Using activemodel 5.0.1
       Using groupdate 3.2.0
       Using jbuilder 2.6.1
       Using rails-html-sanitizer 1.0.3
       Using aws-sdk-resources 2.7.11
       Using omniauth-oauth2 1.4.0
       Using activejob 5.0.1
       Using activerecord 5.0.1
       Using paperclip 5.0.0
       Using actionview 5.0.1
       Using autoscaler 0.12.0
       Using sidekiq-failures 0.4.5
       Using aws-sdk 2.7.11
       Using omniauth-facebook 4.0.0
       Using delayed_paperclip 3.0.1
       Using paperclip-compression 0.3.16
       Using acts_as_list 0.9.2
       Using friendly_id 5.1.0
       Using actionpack 5.0.1
       Using actioncable 5.0.1
       Using actionmailer 5.0.1
       Using railties 5.0.1
       Using sprockets-rails 3.2.0
       Using route_translator 5.1.0
       Using coffee-rails 4.2.1
       Using jquery-rails 4.2.2
       Using rails 5.0.1
       Using sendgrid-rails 3.1.0
       Using breakfast 0.6.0 from https://github.com/devlocker/breakfast (at v0.6.0@0fa5b5f)
       Using cloudflare-rails 0.2.0
       Using nested_form_fields 0.8
       Bundle complete! 49 Gemfile dependencies, 115 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (4.00s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v0.21.3
       warning No license field
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 9.58s.
       Asset precompilation completed (16.02s)
       Cleaning assets
       Running: rake assets:clean
###### WARNING:
       You are deploying to a non-production environment: "staging".
       This is not recommended.
       See https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment for more information.
-----> Discovering process types
       Procfile declares types     -> web, worker
       Default types for buildpack -> console, rake
-----> Compressing...
       Done: 174.6M
-----> Launching...
       Released v302
       deployed to Heroku

**Comment by PatKoperwas** [comment]
😱  Yikes, you are right. I just pushed a fix in https://github.com/devlocker/breakfast/commit/ed274b07f463badaa2a55ba4d968fc5f3e48b10e

Go ahead and run `bundle update breakfast`, still pointing at `0.6.0` and everything _should_ be work

**Comment by Rwobbema** [comment]
Thank you for your quick response!

I've updated the gem and now it's saying that the asset precompilation completed.

```
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 9.71s.
       21:29:14 - info: compiling
       21:29:20 - info: compiling.
       21:36:22 - info: compiling..
       21:36:22 - info: compiled 85 files into 8 files, copied 224 in 434.1 sec
       Asset precompilation completed (450.21s)
       Cleaning assets
       Running: rake assets:clean
```
But I think I'm having a new problem.

```
Refused to execute script from 'https://staging.domain.nl/assets/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
staging.domain.com/:1 Refused to execute script from 'https://staging.domain.nl/assets/employer.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
staging.domain.com/:35 Uncaught ReferenceError: require is not defined
    at staging.domain2.com/:35
```
Hope you can help me with this one too.

**Comment by PatKoperwas** [comment]
Yep. I think I've seen this once before, where a file you `joinTo` in `brunch-config` matches a file in the asset pipeline (or one in an old `.sprockets-manifest`). Can you run these commands for?

```
heroku run bash

// Once bash loads
rm -rf tmp/cache
rails assets:clobber
rails assets:breakfast:compile
exit

// Back on your machine
heroku run restart
```


If that doesn't work can you paste me your `.brunch-config`?

**Comment by Rwobbema** [comment]
This is also not working.

`Don't know how to build task 'assets:breakfast:compile'`

This is what my brunch-config file looks like:

```
module.exports =
  files:
    javascripts:
      joinTo:
        'admin.js': /^app\/frontend\/admin\/js\//
        'employer.js': /^app\/frontend\/employer\/js\//
        'jobseeker.js': /^app\/frontend\/jobseeker\/js\//
        'vendor.js': /^(?!app\/frontend\/admin\/js|app\/frontend\/employer\/js|app\/frontend\/jobseeker\/js)/
    stylesheets:
      joinTo:
        'admin.css': /^app\/frontend\/admin\/css\//
        'employer.css': /^app\/frontend\/employer\/css\//
        'jobseeker.css': /^app\/frontend\/jobseeker\/css\//
        'oldschool.css': /^app\/frontend\/oldschool\/css\//
    templates:
      joinTo: 'app.js'
  plugins:
    babel:
      presets: [ 'es2015' ]
    sass:
      mode: 'native'
      sourceMapEmbed: true
      allowCache: true
      options:
        includePaths: [
          'node_modules/bourbon/app/assets/stylesheets/'
        ]
    postcss:
      map: true
      options:
        parser: [
          require('postcss-scss')
        ]
      processors: [
        require('autoprefixer')([ 'last 2 versions' ]),
        require('postcss-responsive-font'),
        require('postcss-lh')
      ]
    coffeescript:
      bare: true
  paths:
    watched: [
      'app/frontend',
    ]
    public: 'public/assets'
  conventions:
    assets: [
      /^(app\/frontend\/jobseeker\/images)/,
      /^(app\/frontend\/employer\/images)/,
      /^(app\/frontend\/admin\/images)/,
      /^(app\/frontend\/fonts)/,
      /^(node_modules\/font-awesome\/fonts)/
    ]
  npm:
    globals:
      $: 'jquery'
      jQuery: 'jquery'
      breakfast: 'breakfast-rails'
      Highcharts: 'highcharts'
      Chartkick: 'chartkick'
```

**Comment by PatKoperwas** [comment]
Ahh I meant to type `rails breakfast:assets:compile`. Well either way, that hopefully got rid of any weird caches. Does deploying again fix the issue?

If not, are there any files named `vendor.js` in `app/assets/, 'lib/assets/ or vendor/assets`?

**Comment by Rwobbema** [comment]
I don't have any other vender.js files. But something weird seems to happen. After running `rails breakfast:assets:compile` employer.js, admin.js and employer.js are created along with my old application.scss and application.js files. Before compiling the assets I removed the cache and also ran `rails assets:clobber`. But everytime I run `rails breakfast:assets:compile` my old assets are back again.

I can't figure out why this is happening.

**Comment by PatKoperwas** [comment]
@Rwobbema if you'd like to setup a screen share send me an email patrick@devlocker.io. I do not think I can debug what is the issue without seeing it.

**Comment by PatKoperwas** [comment]
Fixed by: Purging Heroku cache
https://github.com/heroku/heroku-repo#purge-cache

And: https://github.com/devlocker/breakfast/commit/d44d373ba3e75fb49f9771d73fad4b46e0afc7e4
