### ISSUE TITLE
Incorrect Guidelines for Elm in Web page

### ISSUE THREAD

**Issue by Aiken00** [devlocker/breakfast#20]
Thank you for creating an awesome gem.

I found there is an error in the guideline of Elm page.

http://breakfast.devlocker.io/examples/elm.html

```
Configure plugin:

plugins: {
  elmBrunch: {
    mainModule: ['app/frontend/js/elm/Main.elm'],
    outputFile: 'elm.js',
    outputFolder: "public/assets/"
  },
```

It should be **mainModules**, a final s is missing.

**Comment by PatKoperwas** [comment]
👍 thanks!
