### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by olivierlacan** [devlocker/breakfast#7]
Do you have any plans to favor yarn over straight npm, since I'd wager most people would benefit from the yarn.lock file? https://yarnpkg.com/

**Comment by PatKoperwas** [comment]
Definitely. It's a bit out of my control (`Breakfast` is really just some glue between [Brunch](https://github.com/brunch/brunch) and Rails) but once Brunch supports it should be available for use in Breakfast.

I don't see any [issues or PRs](https://github.com/brunch/brunch/issues) mentioning `yarn` on the Brunch repo. But `yarn` was just released last week so it might take a bit for it to get on their radar.
