### ISSUE TITLE
Will not run on puma server

### ISSUE THREAD

**Issue by rubylibre** [devlocker/breakfast#9]
I am running a puma server for local development. Probably because of the the condition:
```
defined?(Rails::Server)
```
Any clues on how to get this working via puma?

**Comment by PatKoperwas** [comment]
Hmm it should work with Puma (I'm using Puma). Can you give me a little bit more info about what isn't working?

Mind running this commands in your project folder and pasting the output back here?

```
cat Gemfile.lock | grep "breakfast"
cat Gemfile.lock | grep "rails"
node --version
ruby --version
```

Also what port are you running the server on? If it's something other than `3000` you will probably need to change some ActionCable settings ([see here](http://edgeguides.rubyonrails.org/action_cable_overview.html#allowed-request-origins)) and allow that specific port access.

**Comment by rubylibre** [comment]
First the output
```
$ cat Gemfile.lock | grep "breakfast"
    breakfast (0.3.0)
  breakfast
$ cat Gemfile.lock | grep "rails"
      rails-dom-testing (~> 2.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    autoprefixer-rails (6.5.1)
      rails (~> 5.0)
    dotenv-rails (2.1.1)
    factory_girl_rails (4.7.0)
    jquery-rails (4.2.1)
      rails-dom-testing (>= 1, < 3)
    pry-rails (0.3.4)
    rails (5.0.0.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.1)
    rails-html-sanitizer (1.0.3)
    rails_stdout_logging (0.0.5)
    rspec-rails (3.5.2)
    sass-rails (5.0.6)
      sprockets-rails (>= 2.0, < 4.0)
    sprockets-rails (3.2.0)
      rails (~> 5.0.0)
      rails (>= 3.1)
  autoprefixer-rails
  dotenv-rails
  factory_girl_rails
  jquery-rails
  pry-rails
  rails (~> 5.0.0)
  rails_stdout_logging
  rspec-rails (~> 3.5.0.beta4)
  sass-rails (~> 5.0)
$ node --version
v6.8.1
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
```
Running on port 3000 via 'heroku local' to run the application backed by a Procfile.
I have been testing but Rails::Server does not seem to exist (not defined) in this setup.
But simply skipping defined?(Rails::Server) in railtie.rb does not seem to work.

**Comment by rubylibre** [comment]
Addendum: 
What is not working is that after starting the server I don't see something in the logs like:
`info: compiled 6 files into 3 files in 808ms`
And while I write this I think it could also be just the log.

**Comment by rubylibre** [comment]
After some testing:
The problem is running local development via `heroku local` which uses node-foreman to run the application backed by a Procfile. The Procfile starts rails puma directly, not using rails server, which in it's turn skips Rails::Server. 

I think you use the `defined?(Rails::Server)` to only start the listeners when the proces type is some kind of a server in development mode.

Conclusion: it runs on puma server (but only if called via `rails server`)

**Comment by PatKoperwas** [comment]
And you beat me to it by a minute. 

The check is there to see if we are booting a server [http://guides.rubyonrails.org/initialization.html#rails-server-start](http://guides.rubyonrails.org/initialization.html#rails-server-start). 

After doing a bit of digging though that constant is only run when `rails server` is invoked.

I'll try and figure out a way to make that a bit more flexible.

**Comment by PatKoperwas** [comment]
@rubylibre alright I pushed a fix. Running `bundle exec puma -C config/puma` or `bundle exec rails s puma` now works correctly. 


However, I did notice another issue if you run Puma in clustered mode. For some reason ActionCable subscriptions stop receiving updates in the browser. So if you followed this [Heroku Guide](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) there's one small change you will have to make.

Change `config/puma.rb` to look like this

```
if ENV.fetch("RAILS_ENV") { "development" } != 'development'
  workers Integer(ENV['WEB_CONCURRENCY'] || 2)
  preload_app!

  on_worker_boot do
    # Worker specific setup for Rails 4.1+
    # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
    ActiveRecord::Base.establish_connection
  end
end

threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'
```

It will make things work in development and leave production unchanged. Might take me awhile to figure out the root of the issue.

**Comment by rubylibre** [comment]
It works. ActionCable not receiving updates in the browser might have to do with the (default) async adapter in development environment. That was quick, thanks. I will go and play now :)
